### ISSUE TITLE
New

### ISSUE THREAD

**Issue by Quantum-Codes** [Chiroyce1/weird-js#1]
Make something else to copy when we copy a snippet of code lol

It's possible

**Comment by Chiroyce1** [comment]
Ah yeah I know about that! I was making it locally when you posted this lol 😅

**Comment by Chiroyce1** [comment]
[#03a9563](https://github.com/Chiroyce1/fun-with-js/commit/03a9563ba16f9d59e3007fdde59437ce6b504daa) added it

**Comment by Quantum-Codes** [comment]
You didn't copy this right? 😱
